data PORT_581.AHRF_CO_COMBO;
   set PORT_581.AHRF_CO_COMBO;
   label PctHSConsiderSuicide='% HS students who seriously considered suicide';
   label PctHSMJ='% HS students who took MJ last 30 days';
   label PctAdultMJ='% adults who took MJ last 30 days';
   label PctAdultBinge='% adults who binge drank last 30 days';
   label PctHSSad2Wks ='% HS students who felt sad daily 2+ weeks';
   label PctHSSex = '% HS students who ever had sexual intercourse';
   label medHomValOwnOcc = 'Median home value for owner-occupied housing';
   label MedhouseholdIncome ='Median household income';
   label f1483813 = '% units with > 1 person per room';
   label PctHSProduce ='% HS students who ate fruit 2+ & vegetables 3+ x/day past 7 days';
   label PctAdultActive ='% active adults (150+ min moderate or 75+ min vigorous, weekly)';
   label PctAdultDiabetes = '% adults with diabetes';
   label RateHospStroke  ='Age-adjusted rate of hospns due to stroke (per 100K)';
   label PctAdultPoorHealth  ='% adults who reported fair or poor health';
   label PctAdultInactive ='% adults who are physically inactive';
   label PctHSCigarettes ='% HS students who currently smoke';
   label PctHSObese = '% HS students who are obese';
   label PctHSAsthma ='%HS students ever diagnosed with asthma';
   label PctAdultObese='% adults who are obese';
run;

